In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
import pandas as pd
import numpy as np
url = 'https://raw.githubusercontent.com/tianzedong/cookie-scan/main/Cookies%20-%20cookie-scripts%20audit.csv'
df = pd.read_csv(url)

y_pred = df["pred"].to_numpy()
y_act = df["act"].to_numpy()
print(confusion_matrix(y_act, y_pred))
print(accuracy_score(y_act, y_pred))


[[  6   1   1   1]
 [  0   6   1   2]
 [  0   0  15   8]
 [  0   2   0 156]]
0.9195979899497487
